### ISSUE TITLE
panic: strings: negative Repeat count

### ISSUE THREAD

**Issue by sheeeng** [sibprogrammer/xq#103]
**Problem Statement**

```console
$ xq --version
xq version 1.2.5 (2024-08-29T13:50:34Z, fb8ac87a3431cdfebeeda81053562e3aeebde6af)
```

Got error message from following command.

**Steps to Reproduce**

```shell
curl --silent https://api.politiet.no/politiloggen/v1/rss | xq --html
```

**Actual Result**

```text\
<?xml version="1.0" encoding="utf-16"?>
panic: strings: negative Repeat count

goroutine 7 [running]:
strings.Repeat({0x1030c0426?, 0x140000584e0?}, 0x140000a0de0?)
        strings/strings.go:569 +0x588
github.com/sibprogrammer/xq/internal/utils.FormatHtml({0x1031dc988?, 0x1400007e080?}, {0x1031dca48, 0x140000584e0}, {0x1030c0426, 0x2}, 0x0)
        github.com/sibprogrammer/xq/internal/utils/utils.go:387 +0x680
github.com/sibprogrammer/xq/cmd.init.NewRootCmd.func1.1()
        github.com/sibprogrammer/xq/cmd/root.go:82 +0x224
created by github.com/sibprogrammer/xq/cmd.init.NewRootCmd.func1 in goroutine 1
        github.com/sibprogrammer/xq/cmd/root.go:67 +0x33c
<rss xmlns:a10="http://www.w3.org/2005/Atom" version="2.0">
...
...
```

**Expected Result**

```xml
<?xml version="1.0" encoding="utf-16"?>
<rss xmlns:a10="http://www.w3.org/2005/Atom" version="2.0">
...
...
```

**Comment by sibprogrammer** [comment]
The option `--html` assumes the input in HTML format. It fails in this case because of `link` tag which doesn't assume content in the HTML context.
RSS format is an XML and no additional options are required. But `xq` is fooled by the `utf-16` encoding declaration and produces gibberish in this example. In fact, `xq` has no true UTF-16 support and I probably can workaround this particular problem by UTF-8 enforcement.

**Comment by SharonBrizinov** [comment]
@sibprogrammer 
Thanks for building `xq`, it's a great utility and I find it very useful!

I didn't want to open a new issue so I'm adding a bit more information here as I'm getting a similar crash for even simpler cases, for example on Mac OSX:
```
echo '<!doctype html><a></a></html>' | xq
```

results with -

```
panic: strings: negative Repeat count

goroutine 19 [running]:
strings.Repeat({0x3a0d48e?, 0xc0001303c0?}, 0xc000118dd8?)
        strings/strings.go:569 +0x56b
github.com/sibprogrammer/xq/internal/utils.FormatHtml({0x3b27aa8?, 0xc000094000?}, {0x3b27a68, 0xc0001303c0}, {0x3a0d48e, 0x2}, 0x0)
        github.com/sibprogrammer/xq/internal/utils/utils.go:387 +0x84d
github.com/sibprogrammer/xq/cmd.init.NewRootCmd.func1.1()
        github.com/sibprogrammer/xq/cmd/root.go:82 +0x2b9
created by github.com/sibprogrammer/xq/cmd.init.NewRootCmd.func1 in goroutine 1
        github.com/sibprogrammer/xq/cmd/root.go:67 +0x3ca
```



I did notice that on a Linux machine I need to specify `--html` to reach similar results
```
echo '<!doctype html><a></a></html>' | xq
```

**Comment by sibprogrammer** [comment]
@SharonBrizinov The root cause of the problem in the initial comment was a little bit different. For your use case, it's an attempt to format invalid XML and HTML. Unfortunately, `xq` crashed instead of trying to get the best possible output. The utility definitely will not provide nice-looking XML because the source is invalid, but I will try to handle the errors at least.
