### ISSUE TITLE
Indentation is odd

### ISSUE THREAD

**Issue by exploide** [sibprogrammer/xq#31]
**Problem Statement**

I'm using `xq` for the first time and think I'm encountered an issue with the formatting. As far as I understand, it is supposed to pretty-print the result. When I feed it with an already formatted input, the indentation of the result is odd.

But please correct me if my expectation is wrong. :)

**Steps to Reproduce**
Consider the following as the input and run `xq test.html`:

```html
<body>
    <h1>
        Welcome
    </h1>
    <p>
        Here is no content, yet.
    </p>
</body>
```

**Actual Result**

Now the output of `xq` has the closing tags more deeply indented compared to the opening tags.

```html
<body>
  <h1>
        Welcome
    </h1>
  <p>
        Here is no content, yet.
    </p>
</body>
```

**Expected Result**

I expected that the indentation changed to `xq`'s default of 2 spaces but consistently.

**Comment by sibprogrammer** [comment]
@exploide thank you for your bug report!
It is surprisingly tricky because from the HTML parser point of view, the text node with "Welcome" text, in fact, consists of "newline" + "several spaces" + "Welcome" + "newline" + "several spaces." I can't just "trim" all the whitespace. Need to think about the way how to solve it.
